name: event-detection-transformation
language: Python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: f1-data
    required: false
  - name: output
    inputType: OutputTopic
    defaultValue: hard-braking
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
